from blue import blue
from bold import bold
from cyan import cyan
from default import default
from green import green
from highlight import highlight
from italic import italic
from magenta import magenta
from red import red
from underline import underline
from yellow import yellow
